from .storage_modes import STORAGE_MODE_OPTIONS

SUPPORTED_MANUFACTURERS = ['Fronius']
SUPPORTED_MODELS = ['Primo GEN24', 'Symo GEN24', 'Verto']

SUNSPEC_ID_ADDRESS = 40000
SUNSPEC_FIRST_MODEL_HEADER_ADDRESS = 40002
SUNSPEC_ID_WORD_0 = 0x5375
SUNSPEC_ID_WORD_1 = 0x6E53
SUNSPEC_END_MODEL_ID = 0xFFFF
SUNSPEC_SCAN_MAX_MODELS = 128
SUNSPEC_MAX_MODEL_LENGTH = 4096
SUNSPEC_MODEL_HEADER_WORDS = 2
SUNSPEC_MODEL_MIN_ADDRESS = 40000
SUNSPEC_MODEL_MAX_ADDRESS = 50000
SUNSPEC_MPPT_MODEL_ID = 160
SUNSPEC_STORAGE_MODEL_ID = 124

COMMON_ADDRESS = 40004
INVERTER_ADDRESS = 40071
NAMEPLATE_ADDRESS = 40123
METER_ADDRESS = 40071
INVERTER_MODEL_SETTINGS_ADDRESS = 40151
INVERTER_MODEL_SETTINGS_COUNT = 30
INVERTER_STATUS_ADDRESS = 40183
INVERTER_STATUS_COUNT = 44
INVERTER_CONTROLS_ADDRESS = 40229
INVERTER_CONTROLS_COUNT = 24
STORAGE_ADDRESS = 40345
STORAGE_CONTROL_MODE_ADDRESS = 40348
MINIMUM_RESERVE_ADDRESS = 40350
DISCHARGE_RATE_ADDRESS = 40355
CHARGE_RATE_ADDRESS = 40356
AC_LIMIT_RATE_ADDRESS = 40232
AC_LIMIT_ENABLE_ADDRESS = 40236
OUT_PF_SET_ADDRESS = 40237
OUT_PF_SET_ENABLE_ADDRESS = 40241
CONN_ADDRESS = 40231

CONTROL_STATE_DISABLED = 0
CONTROL_STATE_ENABLED = 1
UINT16_MODULUS = 65536

STORAGE_MODEL_LENGTH = 24
STORAGE_CONTROL_MODE_OFFSET = STORAGE_CONTROL_MODE_ADDRESS - STORAGE_ADDRESS
MINIMUM_RESERVE_OFFSET = MINIMUM_RESERVE_ADDRESS - STORAGE_ADDRESS
DISCHARGE_RATE_OFFSET = DISCHARGE_RATE_ADDRESS - STORAGE_ADDRESS
CHARGE_RATE_OFFSET = CHARGE_RATE_ADDRESS - STORAGE_ADDRESS
MINIMUM_RESERVE_PERCENT_MIN = 5
DEFAULT_MINIMUM_RESERVE_PERCENT = 7
STORAGE_DER_TYPE = 82

MPPT_MODEL_MIN_LENGTH = 20
MPPT_MODEL_MAX_LENGTH = 200
MPPT_MODEL_MIN_REGISTERS = 8
MPPT_MODULE_BLOCK_WORDS = 20
MPPT_MODULE_LABEL_OFFSET = 9
MPPT_MODULE_LABEL_WORDS = 8
MPPT_MODULE_CURRENT_OFFSET = 18
MPPT_MODULE_VOLTAGE_OFFSET = 19
MPPT_MODULE_POWER_OFFSET = 20
MPPT_MODULE_LIFETIME_ENERGY_OFFSET = 21
MPPT_MODULE_TIMESTAMP_OFFSET = 23
MPPT_UNAVAILABLE_U16 = 0xFFFF
MPPT_UNAVAILABLE_U32 = 0xFFFFFFFF

STORAGE_CONTROL_MODE = {
    0: 'auto',
    1: 'charge',
    2: 'discharge',
    3: 'charge_and_discharge',
}

CHARGE_STATUS = {
    1: 'off',
    2: 'empty',
    3: 'discharging',
    4: 'charging',
    5: 'full',
    6: 'holding',
    7: 'testing',
}

INVERTER_STATUS = {
    1: 'off',
    2: 'sleeping',
    3: 'starting',
    4: 'normal',
    5: 'throttled',
    6: 'shutdown',
    7: 'fault',
    8: 'standby',
}

INVERTER_CONTROLS = [
    'Power reduction',
    'Constant reactive power',
    'Constant power factor',
]

INVERTER_EVENTS = [
    'Error',
    'Warning',
    'Info',
]

FRONIUS_INVERTER_STATUS = {
    1: 'off',
    2: 'sleeping',
    3: 'starting',
    4: 'normal',
    5: 'throttled',
    6: 'shutdown',
    7: 'fault',
    8: 'standby',
    9: 'no_solarnet',
    10: 'no_inverter_communication',
    11: 'overcurrent_solarnet',
    12: 'firmware_updating',
    13: 'acfi_event',
}

CHARGE_GRID_STATUS = {
    0: 'disabled',
    1: 'enabled',
}

GRID_STATUS = {
    0: 'off_grid',
    1: 'off_grid_operating',
    2: 'on_grid',
    3: 'on_grid_operating',
}

CONNECTION_STATUS = [ 
    'Connected',
    'Available',
    'Operating',
]

CONNECTION_STATUS_CONDENSED = {
    0: 'disconnected',
    1: 'connected', 
    3: 'available', 
    7: 'operating', 
}

ECP_CONNECTION_STATUS = {
    0: 'disconnected',
    1: 'connected',
}

CONTROL_STATUS = {
    0: 'disabled',
    1: 'enabled',
}

AC_LIMIT_STATUS = {
    0: 'disabled',
    1: 'enabled',
}

STORAGE_EXT_CONTROL_MODE = STORAGE_MODE_OPTIONS
