from .storage_modes import STORAGE_MODE_OPTIONS

SUPPORTED_MANUFACTURERS = ['Fronius']
SUPPORTED_MODELS = ['Primo GEN24', 'Symo GEN24', 'Verto']

SUNSPEC_ID_ADDRESS = 40000
SUNSPEC_FIRST_MODEL_HEADER_ADDRESS = 40002
SUNSPEC_ID_WORD_0 = 0x5375
SUNSPEC_ID_WORD_1 = 0x6E53
SUNSPEC_END_MODEL_ID = 0xFFFF
SUNSPEC_SCAN_MAX_MODELS = 128
SUNSPEC_MAX_MODEL_LENGTH = 4096
SUNSPEC_MODEL_HEADER_WORDS = 2
SUNSPEC_MODEL_MIN_ADDRESS = 40000
SUNSPEC_MODEL_MAX_ADDRESS = 50000
SUNSPEC_MPPT_MODEL_ID = 160
SUNSPEC_STORAGE_MODEL_ID = 124

COMMON_ADDRESS = 40004
INVERTER_ADDRESS = 40071
NAMEPLATE_ADDRESS = 40123
METER_ADDRESS = 40071
INVERTER_MODEL_SETTINGS_ADDRESS = 40151
INVERTER_MODEL_SETTINGS_COUNT = 30
INVERTER_STATUS_ADDRESS = 40183
INVERTER_STATUS_COUNT = 44
INVERTER_CONTROLS_ADDRESS = 40229
INVERTER_CONTROLS_COUNT = 24
STORAGE_ADDRESS = 40345
STORAGE_CONTROL_MODE_ADDRESS = 40348
MINIMUM_RESERVE_ADDRESS = 40350
DISCHARGE_RATE_ADDRESS = 40355
CHARGE_RATE_ADDRESS = 40356
AC_LIMIT_RATE_ADDRESS = 40232
AC_LIMIT_ENABLE_ADDRESS = 40236
OUT_PF_SET_ADDRESS = 40237
OUT_PF_SET_ENABLE_ADDRESS = 40241
CONN_ADDRESS = 40231

CONTROL_STATE_DISABLED = 0
CONTROL_STATE_ENABLED = 1
UINT16_MODULUS = 65536

STORAGE_MODEL_LENGTH = 24
STORAGE_CONTROL_MODE_OFFSET = STORAGE_CONTROL_MODE_ADDRESS - STORAGE_ADDRESS
MINIMUM_RESERVE_OFFSET = MINIMUM_RESERVE_ADDRESS - STORAGE_ADDRESS
DISCHARGE_RATE_OFFSET = DISCHARGE_RATE_ADDRESS - STORAGE_ADDRESS
CHARGE_RATE_OFFSET = CHARGE_RATE_ADDRESS - STORAGE_ADDRESS
MINIMUM_RESERVE_PERCENT_MIN = 5
DEFAULT_MINIMUM_RESERVE_PERCENT = 7
STORAGE_DER_TYPE = 82

MPPT_MODEL_MIN_LENGTH = 20
MPPT_MODEL_MAX_LENGTH = 200
MPPT_MODEL_MIN_REGISTERS = 8
MPPT_MODULE_BLOCK_WORDS = 20
MPPT_MODULE_LABEL_OFFSET = 9
MPPT_MODULE_LABEL_WORDS = 8
MPPT_MODULE_CURRENT_OFFSET = 18
MPPT_MODULE_VOLTAGE_OFFSET = 19
MPPT_MODULE_POWER_OFFSET = 20
MPPT_MODULE_LIFETIME_ENERGY_OFFSET = 21
MPPT_MODULE_TIMESTAMP_OFFSET = 23
MPPT_UNAVAILABLE_U16 = 0xFFFF
MPPT_UNAVAILABLE_U32 = 0xFFFFFFFF

STORAGE_CONTROL_MODE = {
    0: 'Auto',
    1: 'Charge',
    2: 'Discharge',
    3: 'Charge and Discharge',
}

CHARGE_STATUS = {
    1: 'Off',
    2: 'Empty',
    3: 'Discharging',
    4: 'Charging',
    5: 'Full',
    6: 'Holding',
    7: 'Testing',
}

INVERTER_STATUS = {
    1: 'Off',
    2: 'Sleeping',
    3: 'Starting',
    4: 'Normal',
    5: 'Throttled',
    6: 'Shutdown',
    7: 'Fault',
    8: 'Standby',
}

INVERTER_CONTROLS = [
    'Power reduction',
    'Constant reactive power',
    'Constant power factor',
]

INVERTER_EVENTS = [
    'Error',
    'Warning',
    'Info',
]

FRONIUS_INVERTER_STATUS = {
    1: 'Off',
    2: 'Sleeping',
    3: 'Starting',
    4: 'Normal',
    5: 'Throttled',
    6: 'Shutdown',
    7: 'Fault',
    8: 'Standby',
    9: 'No solarnet',
    10: 'No inverter communication',
    11: 'Overcurrent solarnet',
    12: 'Firmware updating',
    13: 'ACFI event',
}

CHARGE_GRID_STATUS = {
    0: 'Disabled',
    1: 'Enabled',
}

GRID_STATUS = {
    0: 'Off grid',
    1: 'Off grid operating',
    2: 'On grid',
    3: 'On grid operating',
}

CONNECTION_STATUS = [ 
    'Connected',
    'Available',
    'Operating',
]

CONNECTION_STATUS_CONDENSED = {
    0: 'Disconnected',
    1: 'Connected', 
    3: 'Available', 
    7: 'Operating', 
}

ECP_CONNECTION_STATUS = {
    0: 'Disconnected',
    1: 'Connected',
}

CONTROL_STATUS = {
    0: 'Disabled',
    1: 'Enabled',
}

AC_LIMIT_STATUS = {
    0: 'Disabled',
    1: 'Enabled',
}

STORAGE_EXT_CONTROL_MODE = STORAGE_MODE_OPTIONS
